import type { ContentItem, PromptTemplate, AppSettings } from './types'

export const MOCK_TEMPLATES: PromptTemplate[] = [
  {
    id: 'tpl_cinematic',
    name: 'Cinematic Landscape',
    body: 'A cinematic wide-angle shot of {topic}, in a {mood} atmosphere. Style: {style}. Shot on 35mm film, high contrast, painterly lighting.',
    contentTypes: ['image', 'video'],
    toneHints: 'cinematic, dark, high contrast',
    negativePrompt: 'low quality, blurry, oversaturated',
    variables: [
      { name: 'topic', description: 'Main subject of the scene' },
      { name: 'mood', description: 'Emotional tone (e.g. melancholic, hopeful)' },
      { name: 'style', description: 'Visual style reference' },
    ],
    usageCount: 12,
    lastUsedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tpl_product',
    name: 'Product Hero Shot',
    body: 'Studio product photography of {product} on a {background} surface. Lighting: {lighting}. Ultra-sharp, commercial quality.',
    contentTypes: ['image', 'carousel'],
    toneHints: 'clean, premium, minimal',
    variables: [
      { name: 'product', description: 'Product to feature' },
      { name: 'background', description: 'Backdrop material/color' },
      { name: 'lighting', description: 'Lighting setup description' },
    ],
    usageCount: 7,
    lastUsedAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tpl_short',
    name: 'Quick Tip Reel',
    body: 'A vertical short-form video explaining {tip} about {topic}. Hook in first 1 second, on-screen text, energetic pace, ending with a clear call to action.',
    contentTypes: ['reel', 'video'],
    toneHints: 'energetic, fast, hook-driven',
    variables: [
      { name: 'tip', description: 'The actionable tip' },
      { name: 'topic', description: 'Subject area' },
    ],
    usageCount: 19,
    lastUsedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tpl_story',
    name: 'Behind The Scenes Story',
    body: 'A behind-the-scenes story showing {moment} from {project}. Casual, authentic, mobile-shot aesthetic.',
    contentTypes: ['story', 'image'],
    toneHints: 'authentic, candid, warm',
    variables: [
      { name: 'moment', description: 'Specific moment to capture' },
      { name: 'project', description: 'Project being worked on' },
    ],
    usageCount: 4,
    lastUsedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

const now = Date.now()

function ago(hours: number): string {
  return new Date(now - hours * 60 * 60 * 1000).toISOString()
}

function ahead(hours: number): string {
  return new Date(now + hours * 60 * 60 * 1000).toISOString()
}

export const MOCK_CONTENT: ContentItem[] = [
  {
    id: 'c001',
    templateId: 'tpl_cinematic',
    templateName: 'Cinematic Landscape',
    generatedPrompt:
      'A cinematic wide-angle shot of a misty mountain valley at dawn, in a melancholic atmosphere. Style: Roger Deakins. Shot on 35mm film, high contrast, painterly lighting.',
    contentType: 'image',
    dimensions: { width: 1920, height: 1080 },
    platforms: ['instagram', 'twitter'],
    status: 'published',
    reviewScore: 9,
    reviewNotes: 'Exceptional composition, perfect mood match.',
    mediaUrl: 'https://picsum.photos/seed/c001/1920/1080',
    thumbnailUrl: 'https://picsum.photos/seed/c001/200/200',
    schedule: { type: 'once', startAt: ago(6) },
    publishedPosts: [
      { platform: 'instagram', postUrl: 'https://instagram.com/p/example1', publishedAt: ago(6) },
      { platform: 'twitter', postUrl: 'https://x.com/example/status/1', publishedAt: ago(6) },
    ],
    createdAt: ago(8),
    publishedAt: ago(6),
  },
  {
    id: 'c002',
    templateId: 'tpl_product',
    templateName: 'Product Hero Shot',
    generatedPrompt:
      'Studio product photography of a brushed-titanium watch on a black slate surface. Lighting: rim-lit from upper-left with soft fill. Ultra-sharp, commercial quality.',
    contentType: 'image',
    dimensions: { width: 1080, height: 1080 },
    platforms: ['instagram', 'pinterest'],
    status: 'reviewing',
    mediaUrl: 'https://picsum.photos/seed/c002/1080/1080',
    thumbnailUrl: 'https://picsum.photos/seed/c002/200/200',
    schedule: { type: 'once', startAt: ago(1) },
    createdAt: ago(2),
  },
  {
    id: 'c003',
    templateId: 'tpl_short',
    templateName: 'Quick Tip Reel',
    generatedPrompt:
      'A vertical short-form video explaining a 3-second productivity hack about deep work. Hook in first 1 second, on-screen text, energetic pace, ending with a clear call to action.',
    contentType: 'reel',
    dimensions: { width: 1080, height: 1920 },
    platforms: ['instagram', 'tiktok', 'youtube'],
    status: 'generating',
    schedule: { type: 'once', startAt: ahead(2) },
    createdAt: ago(0.5),
    scheduledAt: ahead(2),
  },
  {
    id: 'c004',
    templateId: 'tpl_cinematic',
    templateName: 'Cinematic Landscape',
    generatedPrompt:
      'A cinematic wide-angle shot of a neon-lit Tokyo alley at midnight, in a hopeful atmosphere. Style: Wong Kar-wai. Shot on 35mm film.',
    contentType: 'image',
    dimensions: { width: 1080, height: 1350 },
    platforms: ['instagram'],
    status: 'approved',
    reviewScore: 8,
    reviewNotes: 'Solid mood, clean composition.',
    mediaUrl: 'https://picsum.photos/seed/c004/1080/1350',
    thumbnailUrl: 'https://picsum.photos/seed/c004/200/200',
    schedule: { type: 'once', startAt: ahead(6) },
    createdAt: ago(3),
    scheduledAt: ahead(6),
  },
  {
    id: 'c005',
    templateId: 'tpl_story',
    templateName: 'Behind The Scenes Story',
    generatedPrompt:
      'A behind-the-scenes story showing the late-night editing session from the documentary project. Casual, authentic, mobile-shot aesthetic.',
    contentType: 'story',
    dimensions: { width: 1080, height: 1920 },
    platforms: ['instagram', 'facebook'],
    status: 'queued',
    schedule: { type: 'daily', startAt: ahead(20), timeOfDay: '09:00' },
    createdAt: ago(0.2),
    scheduledAt: ahead(20),
  },
  {
    id: 'c006',
    templateId: 'tpl_short',
    templateName: 'Quick Tip Reel',
    generatedPrompt:
      'A vertical short-form video explaining a 1-minute morning routine about focus. Hook in first 1 second, on-screen text.',
    contentType: 'reel',
    dimensions: { width: 1080, height: 1920 },
    platforms: ['tiktok', 'youtube'],
    status: 'rejected',
    reviewScore: 4,
    reviewNotes: 'Hook is weak; pacing inconsistent. Suggest regenerate with stronger opening.',
    mediaUrl: 'https://picsum.photos/seed/c006/1080/1920',
    thumbnailUrl: 'https://picsum.photos/seed/c006/200/200',
    schedule: { type: 'once', startAt: ago(12) },
    createdAt: ago(14),
  },
  {
    id: 'c007',
    templateId: 'tpl_product',
    templateName: 'Product Hero Shot',
    generatedPrompt:
      'Studio product photography of a ceramic coffee mug on a walnut wood surface. Lighting: window-side soft daylight. Ultra-sharp, commercial quality.',
    contentType: 'carousel',
    dimensions: { width: 1080, height: 1080 },
    platforms: ['instagram', 'linkedin'],
    status: 'published',
    reviewScore: 7,
    reviewNotes: 'Good but slight overexposure on highlight.',
    mediaUrl: 'https://picsum.photos/seed/c007/1080/1080',
    thumbnailUrl: 'https://picsum.photos/seed/c007/200/200',
    schedule: { type: 'once', startAt: ago(28) },
    publishedPosts: [
      { platform: 'instagram', postUrl: 'https://instagram.com/p/example7', publishedAt: ago(28) },
      { platform: 'linkedin', postUrl: 'https://linkedin.com/posts/example7', publishedAt: ago(28) },
    ],
    createdAt: ago(30),
    publishedAt: ago(28),
  },
  {
    id: 'c008',
    templateId: 'tpl_cinematic',
    templateName: 'Cinematic Landscape',
    generatedPrompt:
      'A cinematic wide-angle shot of an Icelandic black sand beach, in a stark atmosphere. Style: Emmanuel Lubezki.',
    contentType: 'image',
    dimensions: { width: 1920, height: 1080 },
    platforms: ['instagram', 'twitter', 'facebook'],
    status: 'failed',
    reviewNotes: 'Generation failed: model timeout on attempt 3.',
    schedule: { type: 'once', startAt: ago(48) },
    createdAt: ago(50),
  },
  {
    id: 'c009',
    templateId: 'tpl_short',
    templateName: 'Quick Tip Reel',
    generatedPrompt:
      'A vertical short-form video explaining a 30-second tip about deep work scheduling.',
    contentType: 'reel',
    dimensions: { width: 1080, height: 1920 },
    platforms: ['tiktok', 'instagram'],
    status: 'queued',
    schedule: { type: 'weekly', startAt: ahead(72), timeOfDay: '18:00', daysOfWeek: [1, 3, 5] },
    createdAt: ago(0.1),
    scheduledAt: ahead(72),
  },
  {
    id: 'c010',
    templateId: 'tpl_story',
    templateName: 'Behind The Scenes Story',
    generatedPrompt:
      'A behind-the-scenes story showing the studio setup for the new product launch.',
    contentType: 'story',
    dimensions: { width: 1080, height: 1920 },
    platforms: ['instagram'],
    status: 'approved',
    reviewScore: 8,
    mediaUrl: 'https://picsum.photos/seed/c010/1080/1920',
    thumbnailUrl: 'https://picsum.photos/seed/c010/200/200',
    schedule: { type: 'once', startAt: ahead(4) },
    createdAt: ago(5),
    scheduledAt: ahead(4),
  },
  {
    id: 'c011',
    templateId: 'tpl_product',
    templateName: 'Product Hero Shot',
    generatedPrompt:
      'Studio product photography of leather-bound notebooks stacked on marble. Lighting: soft top key.',
    contentType: 'image',
    dimensions: { width: 1080, height: 1350 },
    platforms: ['pinterest', 'instagram'],
    status: 'published',
    reviewScore: 9,
    reviewNotes: 'Excellent texture rendering.',
    mediaUrl: 'https://picsum.photos/seed/c011/1080/1350',
    thumbnailUrl: 'https://picsum.photos/seed/c011/200/200',
    schedule: { type: 'once', startAt: ago(70) },
    publishedPosts: [
      { platform: 'instagram', postUrl: 'https://instagram.com/p/example11', publishedAt: ago(70) },
      { platform: 'pinterest', postUrl: 'https://pinterest.com/pin/example11', publishedAt: ago(70) },
    ],
    createdAt: ago(72),
    publishedAt: ago(70),
  },
  {
    id: 'c012',
    templateId: 'tpl_cinematic',
    templateName: 'Cinematic Landscape',
    generatedPrompt:
      'A cinematic wide-angle shot of golden-hour wheat fields, in a hopeful atmosphere. Style: Terrence Malick.',
    contentType: 'video',
    dimensions: { width: 1920, height: 1080 },
    platforms: ['youtube', 'instagram'],
    status: 'reviewing',
    mediaUrl: 'https://picsum.photos/seed/c012/1920/1080',
    thumbnailUrl: 'https://picsum.photos/seed/c012/200/200',
    schedule: { type: 'once', startAt: ahead(1) },
    createdAt: ago(0.3),
    scheduledAt: ahead(1),
  },
]

export const MOCK_SETTINGS: AppSettings = {
  agentModels: {
    coordinator: 'claude-sonnet-4-20250514',
    'prompt-engineer': 'claude-sonnet-4-20250514',
    'content-creator': 'flux-1.1-pro',
    reviewer: 'claude-opus-4-5',
    publisher: 'claude-haiku-4-5-20251001',
  },
  reviewThreshold: 7,
  maxRetries: 3,
  notifyOnPublish: true,
  notifyOnFailure: true,
}
